### PR TITLE
Dot product

### PR DESCRIPTION
**Pull request by richy486**
I use this occasionally, might be convenient for others.

### CODE REVIEW

**Comment by PrimaryFeather** [comment]
Thanks, that's useful! I'll have a look at it and will definitely add that to the core. 
Again, thanks for sharing!

**Comment by PrimaryFeather** [comment]
Thanks again, Richy -- I added the change manually. (Finally!)

**Comment by PrimaryFeather** [comment]
(BTW, I chose to implement it as an instance method instead of a static method, because I thought having code like `[p1 dot: p2]` is very pleasant to read.

**Comment by richy486** [comment]
Sounds good

**Pull request closed without merging**
