### PR TITLE
SPTextField Editing

### PR DESCRIPTION
**Pull request by brianensorapps**
I've added editing ability to SPTextField. I see this as an essential ability for game engines.
textField.inputEnabled = YES;

I have also updated the demo.

### CODE REVIEW

**Comment by brianensorapps** [comment]
WAIT. Don't pull yet. I have additions to make:
• Events for keyboard close/open
• Cursor
• Changing insertion point
• Make deletion get faster with longer backspace touch

I will work on it tomorrow.

**Comment by PrimaryFeather** [comment]
Hi Brian,

wow, that looks very promising! Thanks for sharing! :-)

However, I have a suggestion: do you think it would be possible to make this a subclass of SPTextField for now? (Like "SPInputTextField" or similar)? Eventually, it will most probably be added to the SPTextField class directly, just as you do it in your pull request; but that way, people could start immediately using it, simply by adding the class to their game; this would give us the chance to get feedback and/or bug reports for the class, before incorporating it to the core code. 

What do you think of that? Do you think that's doable? Or would you rather leave it that way? It's just a suggestion, of course!

**Comment by PrimaryFeather** [comment]
BTW: 

w00t!!! First pull request! :-)

**Comment by brianensorapps** [comment]
Yes, I'll create a subclass for now. That's a good idea. :)

**Comment by PrimaryFeather** [comment]
Great, thanks Brian! =)

**Pull request closed without merging**
